### PR TITLE
Switch to bintray for publishing

### PR DESCRIPTION
**Pull request by retronym**
Review by @benmccann

### CODE REVIEW

**Comment by benmccann** [comment]
looks fine to me (though i'm not sure i'm particularly qualified to review)

**Comment by retronym** [comment]
@eed3si9n Is this the right approach to migrate a SBT plugin that already has a `-imported` repository under the SBT organization? The docs I found described the way to publish to a personal repository and have that linked into the SBT organization.

**Comment by eed3si9n** [comment]
@retronym It depends on who does most of the publishing. For sbt-assembly I do all of the publishing myself, it uses my personal repository first: https://github.com/sbt/sbt-assembly/blob/master/bintray.sbt:

```scala
bintrayOrganization in bintray := None
```

That's the method described in the [doc](http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html), and I support that method for normal case.

sbt-unidoc on the other hand has switched to using `Some("sbt")` so publishing task can be shared between me and Akka team members.
https://github.com/sbt/sbt-unidoc/blob/master/bintray.sbt

**Comment by retronym** [comment]
@eed3si9n I would like to share the duties with @benmccann, so I think I'll go for direct route. Thanks for the quick reply.

**Comment by retronym** [comment]
Looks like the release worked:

```
% ( java_use 1.6; git log --oneline -1; sbt clean 'set version := "0.8"' clean test publish )
...
[info] Done packaging.
[info] 	published sbt-xjc to org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.8/jars/sbt-xjc.jar
[info] 	published sbt-xjc to org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.8/srcs/sbt-xjc-sources.jar
[info] 	published sbt-xjc to org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.8/docs/sbt-xjc-javadoc.jar
[info] 	published ivy to org.scala-sbt.plugins/sbt-xjc/scala_2.10/sbt_0.13/0.8/ivys/ivy.xml
```

@benmccann I believe you'll also be able to do this as you are a member of the sbt bintray organzation.

/cc @mberndt123

**Comment by mberndt123** [comment]
Hey guys, that was quick! Thanks for that!

2015-07-15 6:46 GMT+02:00 Jason Zaugg <notifications@github.com>:

**Pull request merged**
